version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mybestfriend_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybestfriend_db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql

volumes:
  mysql_data:
